---
tasks:
  - task_name: Produce the Agile Stream 1 Implementation Plan
    work: 8
    work_performed_on: "2021-01-11"
  - task_name: Produce the Agile Stream 1 Implementation Plan
    work: 8
    work_performed_on: "2021-01-12"
  - task_name: Produce the Agile Stream 1 Implementation Plan
    work: 8
    work_performed_on: "2021-01-13"
  - task_name: Produce the Agile Stream 1 Implementation Plan
    work: 8
    work_performed_on: "2021-01-14"
  - task_name: Produce the Agile Stream 1 Implementation Plan
    work: 8
    work_performed_on: "2021-01-15"
