---
tasks:
  -
    task_name: Learning
    work: 8
    work_performed_on: '2021-01-04'
  -
    task_name: Learning
    work: 8
    work_performed_on: '2021-01-05'
  -
    task_name: Learning
    work: 8
    work_performed_on: '2021-01-06'
  -
    task_name: Learning
    work: 8
    work_performed_on: '2021-01-07'
  -
    task_name: Learning
    work: 8
    work_performed_on: '2021-01-08'
