---
tasks:
  - task_name: Learning
    work: 8
    work_performed_on: "2021-03-08"
  - task_name: Learning
    work: 8
    work_performed_on: "2021-03-09"
  - task_name: Learning
    work: 8
    work_performed_on: "2021-03-10"
  - task_name: LZ Deployment
    work: 8
    work_performed_on: "2021-03-11"
  - task_name: Learning
    work: 8
    work_performed_on: "2021-03-12"
